# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CarouselExample' do
pod 'CarouselViewController', '~> 1.0.2'
end

target 'CarouselExampleTests' do

end

target 'CarouselExampleUITests' do

end

